import * as React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/Layout/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className=''>

        </div>
      </Layout>
    </>
  )
}
